# Generated by Django 5.2.17 on 2026-09-21 02:07

import championship.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("done", "Realizada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                ("is_preseason", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["season", "number"],
            },
        ),
        migrations.CreateModel(
            name="ScoringTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                ("data_version", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("nickname", models.CharField(blank=True, max_length=60)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=140),
                ),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "photo",
                    models.CharField(
                        blank=True,
                        help_text="Caminho da versão grande no storage",
                        max_length=255,
                    ),
                ),
                (
                    "photo_thumb",
                    models.CharField(
                        blank=True,
                        help_text="Caminho da miniatura no storage",
                        max_length=255,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "hidden",
                    models.BooleanField(
                        default=False, help_text="Oculta nome e foto no site público"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="championship.category",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="championship.driver",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="imports/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Pré-visualização"),
                            ("confirmed", "Confirmada"),
                            ("undone", "Desfeita"),
                            ("discarded", "Descartada"),
                        ],
                        default="preview",
                        max_length=10,
                    ),
                ),
                ("rows", models.PositiveIntegerField(default=0)),
                ("rows_written", models.PositiveIntegerField(default=0)),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Dados lidos da planilha, gravados na confirmação",
                    ),
                ),
                (
                    "report",
                    models.JSONField(
                        default=dict,
                        help_text="Erros, avisos e resumo da pré-visualização",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "label",
                    models.CharField(help_text="Bateria A, Final…", max_length=40),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="championship.category",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="championship.event",
                    ),
                ),
                (
                    "scoring_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="championship.scoringtable",
                    ),
                ),
            ],
            options={
                "ordering": ["event__number", "order"],
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "start_position",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("best_lap_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("laps", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FIN", "FIN"),
                            ("DNF", "DNF"),
                            ("DSQ", "DSQ"),
                            ("DNS", "DNS"),
                        ],
                        default="FIN",
                        max_length=3,
                    ),
                ),
                ("pole", models.BooleanField(default=False)),
                ("fastest_lap", models.BooleanField(default=False)),
                ("shirt_penalty", models.BooleanField(default=False)),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "sheet_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="championship.category",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="championship.driver",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="championship.importbatch",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="championship.race",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_results",
                        to="championship.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["race", "position"],
            },
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("time", "Tempo"),
                            ("position", "Posição"),
                            ("dsq", "Desclassificação"),
                            ("stop_go", "Stop & Go"),
                            ("other", "Outra"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "seconds",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("positions", models.PositiveSmallIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalty_set",
                        to="championship.raceresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("points", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="championship.scoringtable",
                    ),
                ),
            ],
            options={
                "ordering": ["table", "position"],
            },
        ),
        migrations.AddField(
            model_name="scoringtable",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_tables",
                to="championship.season",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="championship.season",
            ),
        ),
        migrations.CreateModel(
            name="SeasonConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discards", models.PositiveSmallIntegerField(default=2)),
                ("consistency_top_n", models.PositiveSmallIntegerField(default=5)),
                (
                    "tiebreak_order",
                    models.JSONField(default=championship.models.default_tiebreak),
                ),
                (
                    "pole_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "fastest_lap_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "fastest_lap_min_position",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Bônus de VR só para quem termina nesta posição ou pior (4 = fora do pódio)",
                    ),
                ),
                (
                    "dnf_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "shirt_penalty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "season",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="championship.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upto_event", models.PositiveSmallIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "previous_position",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("points", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "points_with_discard",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("races", models.PositiveSmallIntegerField(default=0)),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("podiums", models.PositiveSmallIntegerField(default=0)),
                ("poles", models.PositiveSmallIntegerField(default=0)),
                ("fastest_laps", models.PositiveSmallIntegerField(default=0)),
                (
                    "gap_to_leader",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("per_event", models.JSONField(default=dict)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="championship.category",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="championship.driver",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="championship.season",
                    ),
                ),
            ],
            options={
                "ordering": ["season", "category", "upto_event", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="raceresult",
            index=models.Index(
                fields=["category", "driver"], name="championshi_categor_2903e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raceresult",
            index=models.Index(
                fields=["race", "category", "position"],
                name="championshi_race_id_49de7d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="raceresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("race", "driver"),
                name="uniq_active_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="scoringrule",
            constraint=models.UniqueConstraint(
                fields=("table", "position"), name="uniq_rule_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.UniqueConstraint(
                fields=("event", "label", "category"), name="uniq_race_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="scoringtable",
            constraint=models.UniqueConstraint(
                fields=("season", "name"), name="uniq_table_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("season", "number"), name="uniq_event_number"
            ),
        ),
        migrations.AddIndex(
            model_name="standing",
            index=models.Index(
                fields=["season", "category", "upto_event"],
                name="championshi_season__9f7ecb_idx",
            ),
        ),
    ]
