# Generated by Django 5.2.17 on 2026-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0002_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonconfig",
            name="discard_absences",
            field=models.BooleanField(
                default=True,
                help_text="Corridas que o piloto não disputou também podem ser descartadas (valem 0)",
            ),
        ),
    ]
