# Generated by Django 5.2.17 on 2026-09-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0003_discard_absences"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonconfig",
            name="podium_positions",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Quantos primeiros colocados contam como pódio (RKR: até o 5º)",
            ),
        ),
    ]
