# Generated by Django 5.2.17 on 2026-09-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0004_podium_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="schedule",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="track_art",
            field=models.CharField(
                blank=True,
                help_text="Traçado redesenhado para as artes",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="track_direction",
            field=models.CharField(
                blank=True,
                choices=[("cw", "Horário"), ("ccw", "Anti-horário")],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="track_image",
            field=models.CharField(
                blank=True, help_text="Traçado original enviado", max_length=255
            ),
        ),
    ]
